name: check_install_plugin
description: Flutter plugin for check APK is install.
author: xq<chenbaoqian57@gmail.com>
version: 0.0.1
homepage: https://github.com/xq-life/check_install_plugin


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.xq.check_install_plugin
        pluginClass: CheckInstallPlugin
      ios:
        pluginClass: CheckInstallPlugin
